# NumPy Arrays

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
#importing numpy:
import numpy as np
arr = np.array(my_list)

NameError: name 'my_list' is not defined

In [3]:
arr

array([1, 2, 3])

In [7]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_list)

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#Using arange
#arange is exactly what range function deos,i.e...

print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [9]:
#Using linspace:
#linspace takes three arguments ,starting point,end point and how many numbers user want . It splits the range in equal proportion,i.e

print(np.linspace(0,1,10))
print(np.linspace(0,10,15))

#Note : It creates 1-D array's(vectors) only..

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [10]:
#using eye 
#eye is used to create identity matrices.....
import numpy as np
print(np.eye(3))
print('\n')
print(np.eye(2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0.]
 [0. 1.]]


In [9]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#random : 

#prints random numbers in range 0-1
print(np.random.rand(3))
print('\n')

print(np.random.rand(2,5))

[0.34294185 0.64556071 0.41751727]


[[0.34475581 0.76410956 0.94621712 0.30167929 0.15950146]
 [0.16132064 0.89574937 0.2936277  0.31024227 0.51866634]]


In [12]:
print(np.random.randint(0,100,5))# Prints n integers between 0(inclusive)-100(exclusive) 

[51 14 31 20 17]


In [15]:
print(np.random.randint(0,101,15))

[31 70 96 54 57  2  3 62 83 93 99 47  8  6 23]


# why use Numpy:



In [20]:
import time

#Printing time to get mean of very big arrays:
start = time.time()
arr = np.random.random(10000000)
sum(arr)/len(arr)#conventional Method
print(time.time()-start)

6.503717422485352


In [16]:
#Printing time to get mean of very big arrays
start = time.time()
arr = np.random.randint(0,1000000,100000)
np.mean(arr)
print(time.time()-start)

0.016669273376464844


In [36]:
#Other Useful methos : 

array = np.arange(1,26)

print(array.shape)

print(array.reshape(5,5))

print(array.max())

print(array.min())

print(array.dtype)

print(array.argmax())#prints the position of maximum value in the array...

(25,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
25
1
int32
24
