# NumPy Arrays

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
#importing numpy:
import numpy as np
arr = np.array(my_list)

NameError: name 'my_list' is not defined

In [3]:
arr

array([1, 2, 3])

In [7]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_list)

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#Using arange
#arange is exactly what range function deos,i.e...

print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [9]:
#Using linspace:
#linspace takes three arguments ,starting point,end point and how many numbers user want . It splits the range in equal proportion,i.e

print(np.linspace(0,1,10))
print(np.linspace(0,10,15))

#Note : It creates 1-D array's(vectors) only..

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [10]:
#using eye 
#eye is used to create identity matrices.....
import numpy as np
print(np.eye(3))
print('\n')
print(np.eye(2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0.]
 [0. 1.]]


In [9]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#random : 

#prints random numbers in range 0-1
print(np.random.rand(3))
print('\n')

print(np.random.rand(2,5))

[0.34294185 0.64556071 0.41751727]


[[0.34475581 0.76410956 0.94621712 0.30167929 0.15950146]
 [0.16132064 0.89574937 0.2936277  0.31024227 0.51866634]]


In [12]:
print(np.random.randint(0,100,5))# Prints n integers between 0(inclusive)-100(exclusive) 

[51 14 31 20 17]


In [15]:
print(np.random.randint(0,101,15))

[31 70 96 54 57  2  3 62 83 93 99 47  8  6 23]


# why use Numpy:



In [20]:
import time

#Printing time to get mean of very big arrays:
start = time.time()
arr = np.random.random(10000000)
sum(arr)/len(arr)#conventional Method
print(time.time()-start)

6.503717422485352


In [16]:
#Printing time to get mean of very big arrays
start = time.time()
arr = np.random.randint(0,1000000,100000)
np.mean(arr)
print(time.time()-start)

0.016669273376464844


In [36]:
#Other Useful methos : 

array = np.arange(1,26)

print(array.shape)

print(array.reshape(5,5))

print(array.max())

print(array.min())

print(array.dtype)

print(array.argmax())#prints the position of maximum value in the array...

(25,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
25
1
int32
24


# Slicing and Indexing

In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[2]

3

In [39]:
arr[:3]

array([1, 2, 3])

In [40]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [41]:
arr[4:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
#2-D array:


In [43]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr[0][2]

3

In [46]:
arr[0,2]

3

In [47]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [49]:
arr = np.arange(1,51).reshape(5,10)

In [50]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [52]:
#For getting 38
arr[3,7]

38

In [58]:
#For getting 17,18,27,28
arr[1:3,6:8]

array([[17, 18],
       [27, 28]])

In [59]:
#For getting 23,33,24,34
arr[2:4,2:4]

array([[23, 24],
       [33, 34]])

# Numpy Operations:

In [60]:
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [64]:
arr-100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [65]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [66]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [68]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [69]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [70]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [71]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
np.max(arr)

10

In [73]:
np.min(arr)

1